Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssignMVC;

namespace AssignMVC.Controllers
{
    [Authorize]
    public class DepartmentsController : Controller
    {
        private assignEntities db = new assignEntities();

        // GET: Departments
        public ActionResult Index()
        {
            return View(db.Department.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentID,DepartmentName,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate,Status")] Department department)
        {
            if (ModelState.IsValid)
            {
                department.CreatedBy = "Tanzeel";
                department.CreatedDate = DateTime.Now;
                department.UpdatedBy = "Tanzeel";
                department.UpdatedDate = DateTime.Now;
                department.Status = true;
                db.Department.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentID,DepartmentName,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate,Status")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: Departments/Delete/5
             public ActionResult Delete(int? id)
                {
                  /*  if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Department department = db.Department.Find(id);
                    if (department == null)
                    {
                        return HttpNotFound();
                    }
                    return View(department);*/
                assignEntities db = new assignEntities();
                var depart = db.Department.Find(id);
                depart.Status = !depart.Status;
                db.Entry(depart).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
    }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            /*            Department department = db.Department.Find(id);
                        db.Department.Remove(department);
                        db.SaveChanges();
                        return RedirectToAction("Index");*/
            assignEntities db = new assignEntities();
            var depart = db.Department.Find(id);
            depart.Status = false;
            db.Entry(depart).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Scripts.Render("~/bundles/jquery")
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Kendo")
    @Styles.Render("~/Kendo/styles")
    <script src="~/kendoui/js/jquery.min.js"></script>
    <script src="~/kendoui/js/kendo.all.min.js"></script>
    <link href="https://kendo.cdn.telerik.com/2021.1.330/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2021.1.330/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.1.330/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.1.330/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.1.330/js/kendo.aspnetmvc.min.js"></script>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.914/styles/kendo.common.min.css" />
    @*    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.914/styles/kendo.blueopal.min.css" />*@
    <script>
        function logout() {
            return confirm('Are you sure, You want to Logout?');
        }
    </script>

</head>
<body>

    <style>
        body {
            font-family: @*'Poppins', sans-serif*@'Times New Roman', Times, serif;
            background: #fafafa;
            padding: 0;
            margin: 0;
        }

        p {
            font-family: 'Poppins', sans-serif;
            font-size: 1.1em;
            font-weight: 300;
            line-height: 1.7em;
            color: #999;
        }

        a,
        a:hover,
        a:focus {
            color: inherit;
            text-decoration: none;
            transition: all 0.3s;
        }

        .navbar {
            padding: 15px 10px;
            background: #fff;
            border: none;
            border-radius: 0;
            margin-bottom: 40px;
            box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
        }

        .navbar-btn {
            box-shadow: none;
            outline: none !important;
            border: none;
        }

        .line {
            width: 100%;
            height: 1px;
            border-bottom: 1px dashed #ddd;
            margin: 40px 0;
        }

        .wrapper {
            display: flex;
            width: 100%;
            align-items: stretch;
        }

        #sidebar {
            min-width: 250px;
            max-width: 250px;
            background: #0e2f44;
            color: #fff;
            transition: all 0.3s;
        }

            #sidebar.active {
                margin-left: -250px;
            }

            #sidebar .sidebar-header {
                padding: 20px;
                background: #0e2f44;
            }

            #sidebar ul.components {
                padding: 20px 0;
                border-bottom: 1px solid #47748b;
            }

            #sidebar ul p {
                color: #fff;
                padding: 10px;
            }

            #sidebar ul li a {
                padding: 10px;
                font-size: 1.1em;
                display: block;
            }

                #sidebar ul li a:hover {
                    color: #7386D5;
                    background: #fff;
                }

            #sidebar ul li.active > a,
            a[aria-expanded="true"] {
                color: #fff;
                background: #468499;
            }

        a[data-toggle="collapse"] {
            position: relative;
        }

        .dropdown-toggle::after {
            display: block;
            position: absolute;
            top: 50%;
            right: 20px;
            transform: translateY(-50%);
        }

        ul ul a {
            font-size: 0.9em !important;
            padding-left: 30px !important;
            background: #c0d6e4;
            color:black;
        }

        ul.CTAs {
            padding: 20px;
        }

            ul.CTAs a {
                text-align: center;
                font-size: 0.9em !important;
                display: block;
                border-radius: 5px;
                margin-bottom: 5px;
            }

        a.download {
            background: #fff;
            color: #7386D5;
        }

        a.article,
        a.article:hover {
            background: #6d7fcc !important;
            color: #fff !important;
        }

        #content {
            width: 100%;
            padding: 20px;
            min-height: 100vh;
            transition: all 0.3s;
        }

    </style>


    <div class="wrapper">
        @if (User.Identity.IsAuthenticated)
        {
            <nav id="sidebar">

                <div class="sidebar-header">
                    <img src="~/logo/1.png" style="width:210px; height:auto; border-radius:8%" alt=" Load" />
                    <h3 style="display:inline-block;">Welcome </h3><h4 style="display:inline-block">&nbsp;&nbsp;@Session["username"]</h4> 
                </div>

                <ul class="list-unstyled components">
                    <li>
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Manage Employee</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                @Html.ActionLink("Employee Records", "List", "Home")
                            </li>
                            <li>
                                @Html.ActionLink("Employee Chart", "Index", "Home")
                            </li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Department Records", "Index", "Departments")
                    </li>
                    <!--<li>
                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li>
                                <a href="#">-->@*Page 1*@<!--</a>
                            </li>
                            <li>
                                <a href="#">-->@*Page 2*@<!--</a>
                            </li>
                            <li>
                                <a href="#">-->@*Page 3*@<!--</a>
                            </li>
                        </ul>
                    </li>-->


                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>

                </ul>

                <ul class="list-unstyled CTAs">
                    <li>
                    </li>
                    <li>
                    <li>
                    </li>
                </ul>
            </nav>
        }
    <div id="content">
        @if (User.Identity.IsAuthenticated)
        {
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span></span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <i class="fas fa-home" style="position:relative; top:2px; right:2px; "></i>@Html.MvcSiteMap().SiteMapPath()
                            @*                            <asp:SiteMapDataSource runat="server"></asp:SiteMapDataSource>
        <asp:SiteMapPath PathSeparator=">" ren runat="server"></asp:SiteMapPath>
        <li class="nav-item active"><a class="nav-link" href="/Home"><i class="fas fa-h-square"></i> > Manage Employee</a></li>*@
                        </ul>
                    </div>
                </div>
            </nav>}
        @RenderBody()
    </div>
        </div>
    

        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>

@*        <script src="https://kendo.cdn.telerik.com/2021.3.914/js/kendo.all.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>*@
        <script>
            $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                });
            });
        </script>
@*        @Scripts.Render("~/bundles/jquery")*@
@*        @Scripts.Render("~/bundles/bootstrap")*@
        @RenderSection("scripts", required: false)
    </body>
</html>